/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vue;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import javax.swing.BorderFactory;
import javax.swing.JPanel;

/**
 *
 * @author acassard
 */
public class JPanelBataille extends javax.swing.JPanel {

    private JPanel JPanelLeftBar;
    /**
     * Creates new form JPanelBataille
     */
    public JPanelBataille() {
        initComponents();
        FlowLayout layout = (FlowLayout) this.getLayout();
        this.JPanelLeftBar = new JPanel();
        this.JPanelLeftBar.setPreferredSize(new Dimension(150,700));
        this.JPanelLeftBar.setBorder(BorderFactory.createLineBorder(Color.black));
        layout.setAlignment(FlowLayout.LEADING);
        this.add(JPanelLeftBar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setPreferredSize(new java.awt.Dimension(1200, 800));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
