/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vue;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.SwingConstants;

/**
 *
 * @author acassard
 */
public class JPanelAccueil extends javax.swing.JPanel {

    /**
     * Creates new form JPanelAccueil
     */
    public JPanelAccueil() {
        initComponents();
        ImageIcon mate = new ImageIcon(this.getClass().getResource("/resources/img/mate.png"));
        Image scaledImg = mate.getImage().getScaledInstance(150, 150, Image.SCALE_SMOOTH);
        jLabel1.setIcon(new ImageIcon(scaledImg));
        jLabel1.setText(null);
        jLabel1.setIconTextGap(0);
        jLabel1.setHorizontalAlignment(SwingConstants.LEFT);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelTitre = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1Joueur = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(138, 10), new java.awt.Dimension(138, 10), new java.awt.Dimension(138, 10));
        jButton2Joueur = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(138, 10), new java.awt.Dimension(138, 10), new java.awt.Dimension(138, 10));
        jButtonRegles = new javax.swing.JButton();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(138, 10), new java.awt.Dimension(138, 10), new java.awt.Dimension(138, 10));
        jButtonQuitter = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(800, 600));

        jPanel1.setPreferredSize(new java.awt.Dimension(260, 54));

        jLabelTitre.setFont(new java.awt.Font("Cantarell Extra Bold", 0, 36)); // NOI18N
        jLabelTitre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitre.setText("Bataille Navale");
        jPanel1.add(jLabelTitre);

        jPanel2.setOpaque(false);
        jPanel2.setPreferredSize(new java.awt.Dimension(138, 140));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));

        jButton1Joueur.setText("Joueur vs Ordi");
        jButton1Joueur.setAlignmentX(0.5F);
        jButton1Joueur.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1Joueur.setPreferredSize(new java.awt.Dimension(138, 25));
        jPanel2.add(jButton1Joueur);
        jPanel2.add(filler1);

        jButton2Joueur.setText("Joueur vs Joueur");
        jButton2Joueur.setAlignmentX(0.5F);
        jButton2Joueur.setEnabled(false);
        jPanel2.add(jButton2Joueur);
        jPanel2.add(filler2);

        jButtonRegles.setText("Règles");
        jButtonRegles.setAlignmentX(0.5F);
        jPanel2.add(jButtonRegles);
        jPanel2.add(filler3);

        jButtonQuitter.setText("Quitter");
        jButtonQuitter.setAlignmentX(0.5F);
        jPanel2.add(jButtonQuitter);

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(275, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(265, 265, 265))
            .addGroup(layout.createSequentialGroup()
                .addGap(331, 331, 331)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 176, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.JButton jButton1Joueur;
    private javax.swing.JButton jButton2Joueur;
    private javax.swing.JButton jButtonQuitter;
    private javax.swing.JButton jButtonRegles;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelTitre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

    public JButton getjButton1Joueur() {
        return jButton1Joueur;
    }        

    public JButton getjButtonQuitter() {
        return jButtonQuitter;
    }

    public JButton getjButtonRegles() {
        return jButtonRegles;
    }

}
